Switch to wzrd from beefy
Got this unusual error with beefy (TODO: also try https://github.com/mattdesl/budo):

voxelmetaverse $ npm start

> voxelmetaverse@0.0.1 start /Users/admin/games/voxeljs/voxelmetaverse
> beefy index.js:bundle.js --watchify --port 8080 -- --debug

beefy (v2.1.5) is listening on http://127.0.0.1:8080
200    5ms       778B  /
buffer.js:238
    buf.copy(buffer, pos);
        ^

TypeError: buf.copy is not a function
    at Function.Buffer.concat (buffer.js:238:9)
    at Stream.end (/Users/admin/games/voxeljs/voxelmetaverse/node_modules/beefy/lib/accumulate-error.js:25:26)
    at _end (/Users/admin/games/voxeljs/voxelmetaverse/node_modules/beefy/node_modules/through/index.js:61:9)
    at Stream.stream.end (/Users/admin/games/voxeljs/voxelmetaverse/node_modules/beefy/node_modules/through/index.js:70:5)
    at Stream.onend (stream.js:59:10)
    at emitNone (events.js:72:20)
    at Stream.emit (events.js:166:7)
    at drain (/Users/admin/games/voxeljs/voxelmetaverse/node_modules/beefy/node_modules/through/index.js:33:23)
    at Stream.stream.queue.stream.push (/Users/admin/games/voxeljs/voxelmetaverse/node_modules/beefy/node_modules/through/index.js:41:5)
    at Stream.end (/Users/admin/games/voxeljs/voxelmetaverse/node_modules/beefy/node_modules/through/index.js:17:35)

npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/admin/.nvm/versions/node/v4.2.4/bin/node" "/Users/admin/.nvm/versions/node/v4.2.4/bin/npm" "start"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! voxelmetaverse@0.0.1 start: `beefy index.js:bundle.js --watchify --port 8080 -- --debug`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the voxelmetaverse@0.0.1 start script 'beefy index.js:bundle.js --watchify --port 8080 -- --debug'.
npm ERR! This is most likely a problem with the voxelmetaverse package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     beefy index.js:bundle.js --watchify --port 8080 -- --debug
npm ERR! You can get their info via:
npm ERR!     npm owner ls voxelmetaverse
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/admin/games/voxeljs/voxelmetaverse/npm-debug.log