Remove browserify-commit-sha for now
Got this weird error I don't understand (since line 5 of index.js
doesn't have any unterminated string constants):

oxelmetaverse $ npm start

> voxelmetaverse@0.0.1 start /Users/admin/games/voxeljs/voxelmetaverse
> wzrd index.js:bundle.js --watchify --port 8080 -- --debug

server started at http://localhost:8080
{"url":"/logo-white.png","type":"static","time":"2016-01-10T21:44:47.143Z"}
{"url":"/crosshair4.png","type":"static","time":"2016-01-10T21:44:47.153Z"}
{"url":"/bundle.js","type":"bundle","command":"browserify index.js --debug","elapsed":"228ms","time":"2016-01-10T21:44:47.378Z"}
SyntaxError: Unterminated string constant (5:45) while parsing /Users/admin/games/voxeljs/voxelmetaverse/index.js while parsing file: /Users/admin/games/voxeljs/voxelmetaverse/index.js
    at DestroyableTransform.end [as _flush] (/Users/admin/games/voxeljs/voxelmetaverse/node_modules/browserify/node_modules/insert-module-globals/index.js:96:21)
    at DestroyableTransform.<anonymous> (/Users/admin/games/voxeljs/voxelmetaverse/node_modules/browserify/node_modules/readable-stream/lib/_stream_transform.js:123:12)
    at DestroyableTransform.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at prefinish (/Users/admin/games/voxeljs/voxelmetaverse/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:501:12)
    at finishMaybe (/Users/admin/games/voxeljs/voxelmetaverse/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:509:7)
    at endWritable (/Users/admin/games/voxeljs/voxelmetaverse/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:521:3)
    at DestroyableTransform.Writable.end (/Users/admin/games/voxeljs/voxelmetaverse/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:486:5)
    at DuplexWrapper.onend (/Users/admin/games/voxeljs/voxelmetaverse/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:545:10)